config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  resources :guest_lists
  resources :djs, only: [:index, :show]
  resources :party_goers, only: [:show, :new, :create]
  resources :promoters, only: [:index, :show]
  
  post '/parties/:party_id/party_goers', to: 'party_goers#attend', as: 'attend_party'
  
  
  resources :parties, only: [:index, :show] do
    resources :reviews, except: [:index, :show]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dj.rb
class Dj < ApplicationRecord
    has_many :parties

    def dj_party
        self.parties.map do|party|
            party.name
        end.join
    end

    def dj_party_count
       self.parties.count
    end
    

    def self.most_parties
      self.all.max_by do |dj|
        dj.parties.count
      end
    end
    
end

app/models/guest_list.rb
class GuestList < ApplicationRecord
    belongs_to :party
    belongs_to :party_goer

end

app/models/party.rb
class Party < ApplicationRecord
    belongs_to :promoter
    belongs_to :dj
    has_many :guest_lists
    has_many :party_goers, through: :guest_lists
    has_many :reviews

 def review_title
    self.reviews.map do |review|
        review.title
    end.join 
 end

 def average_rating
   rate = self.reviews.map do |review|
        review.rating 
    end
    rate.sum/rate.length.to_f
 end

 def num_of_guests
    self.party_goers.count
 end

#  def highest_guestlist

#  end

 def party_genre
    self.dj.genre 
 end
 
end

app/models/party_goer.rb
class PartyGoer < ApplicationRecord
    has_secure_password

    has_many :guest_lists
    has_many :parties, through: :guest_lists
    has_many :reviews

    validates :username, presence: true
    validates :age, numericality: {only_integer: true}


    def parties_names
        self.parties.map  do |party|
            party.name
        end.join
    end

    def party_reviewed
        
        self.reviews.map do |review|
        review.content
        end.join(" , ")
    end
    
    def party_count
        self.parties.count
    end

    def favorite_party
        self.reviews.map do |rating|
            rating
        end.max
    end
end

app/models/promoter.rb
class Promoter < ApplicationRecord
    has_many :parties

    def promoter_party
        self.parties.map do|party|
            party.name
        end.join
    end

    def party_count
        self.parties.count
    end
    
    # def highest_reviewed
    #     self.parties.each  do |party|
    #         party.reviews.ratings
    #     end
    # end
end

# How many parties a promoter has
# Highest reviewed party

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :party
    belongs_to :party_goer

    validates :title,  length: {minimum: 3} 
    validates :content, length: { minimum: 3}

    def self.highest_rated_party
        rate = self.all.map  do |rating|
            rating 
        end
        rate.max
    end

    def reviewed_by
        self.party_goer.username
    end
    
    # def reviewed_for
        
    # end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   helper_method :current_user

  def current_user
    @user = (PartyGoer.find_by(id: session[:user_id]) || PartyGoer.new)
  end

  def logged_in?
    # current_user.id != nil
    !!current_user
  end

  def require_logged_in
    return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  end
  
end

app/controllers/djs_controller.rb
class DjsController < ApplicationController

    def index
        @djs = Dj.all
    end

    def show
        @dj = Dj.find(params[:id])
    end
    
    
    
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

    def index
        @parties = Party.all
    end

    def show
        @party = Party.find(params[:id])
    end

    
    

    private

    def party_params
        params.require(:party).permit(:name, :location, :date, :party_id, :promoter_id)
    end
end

app/controllers/promoters_controller.rb
class PromotersController < ApplicationController

    def index
        @promoters = Promoter.all
    end
    
    def show
        @promoter = Promoter.find(params[:id])
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_logged_in

    def new
        @review = Review.new
        @party = Party.find(params[:party_id])
    end

    def create
        @review = Review.new(review_params)
        @party = Party.find(params[:party_id])
        # @review.party = @party
        # @review.party = current_user
         if @review.valid?
            @review.save
            redirect_to party_path(@review.party)
        else 
            render :new
        end
    end

    def edit
        @review = Review.find(params[:id])

    end

    def update
        @review = Review.find(params[:id])
        @review.update(review_params)
        redirect_to party_path(@review.party)
    end

    def destroy
        @review = Review.find(params[:id])
        @review.delete
        redirect_to party_path(@review.party)
    end

    private

    def review_params
        params.require(:review).permit(:title, :content, :rating, :party_goer_id, :party_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    
    username = params[:username]
    @user = PartyGoer.find_by(username: username)
    if @user && @user.authenticate(params[:password])
     session[:user_id] = @user.id 
      flash[:message] = "Party Goer is logged in"
      redirect_to parties_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/d_js_helper.rb
module DJsHelper
end

app/helpers/guest_lists_helper.rb
module GuestListsHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/party_goers_helper.rb
module PartyGoersHelper
end

app/helpers/promoters_helper.rb
module PromotersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/djs/index.html.erb
<h1>DJ List</h1>

<ul>
    <% @djs.each do|dj| %> 
      <li><%= link_to dj.name, dj_path(dj)%></li>
      <% end %>
</ul>

app/views/djs/show.html.erb
<h3><%=@dj.name%>'s Detail Page</h3>

<div><strong>Name: </strong><%= @dj.name %></div>
<div><strong>Genre: </strong><%= @dj.genre%></div>
<div><strong>Tagline: </strong> <em>"<%= @dj.tagline%>"</em></div>

<div><strong>DJ Parties: </strong></div>
 <% @dj.parties.each do |party|%>
<li><%= link_to party.name, party_path(party.id)%></li>
<% end %>

app/views/parties/index.html.erb
<h1 class= "title is-2">List of Parties</h1>
<ul>
    <% @parties.each do|party| %>
   <li> <%= link_to party.name, party_path(party) %></li>
        <%= "Location - #{party.location}"%>

   <%end%>
</ul>
        <%= link_to "My Parties", party_goer_path(current_user)%>

app/views/parties/show.html.erb
<h1><%=@party.name%> Detail Page</h1>
<div><strong>Location: </strong><%= @party.location%></div>
<div><strong>Date:</strong> <%= @party.date.strftime("%B %d, %Y")%><br>


<div><strong>Promoter: </strong> <%= link_to @party.promoter.name, promoter_path(@party.promoter)%><br>
<div><strong>DJ: </strong> <%= link_to @party.dj.name, dj_path(@party.dj)%>
<div><strong>Reviews:</strong> </div> 
    <ul>
        <% @party.reviews.each do|review| %>

        <li><%= review.title %></li>
        <%= review.content%> 
         <div>Rating: <%=review.rating%></div>



        <%end%>
    </ul>

<%=link_to "Review This Party", new_party_review_path(@party.id)%><br>

 <%= button_to "Add Party to Party List", attend_party_path(@party.id) %>
 <%= link_to "Back to Parties", parties_path%>

app/views/promoters/index.html.erb
<h1>Promoters Page</h1>

<ul>
    <%@promoters.each do |promoter| %>
    <li><%= link_to promoter.name, promoter_path(promoter)%></li>
    <% end %>
</ul>

app/views/promoters/show.html.erb
<h3><%= @promoter.name %>'s Detail Page</h3>

 <% @promoter.parties.each  do |party| %>
       <%= link_to party.name, party_path(@promoter.party_ids) %><br>
        <%end %>




 